# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: go-buildinfo
  # You may pin to the exact commit or the version.
  # uses: zaibon/go-buildinfo@2ff4ebe5d29fe238d301404ef0a4fb075bc61b7d
      uses: wukuili/sonic@0.1.0
      # with:
      #   # Specify release version to use. Automatically determined if unset.
      #   release_version: # optional
          
